apiVersion: skaffold/v2beta12
kind: Config
build:
  local: 
    push: false
  artifacts:
    - image: tmwarne/multi-client
      context: client
      docker:
        dockerfile: Dockerfile.dev
      sync: 
        manual: 
          - src: 'src/**/*.js'
            dest: .
          - src: 'src/**/*.css'
            dest: .
          - src: 'src/**/*.html'
            dest: .
    - image: tmwarne/multi-worker
      context: worker
      docker:
        dockerfile: Dockerfile.dev
      sync: 
        manual: 
          - src: 'src/**/*.js'
            dest: .
          - src: 'src/**/*.css'
            dest: .
          - src: 'src/**/*.html'
            dest: .
    - image: tmwarne/multi-server
      context: server
      docker:
        dockerfile: Dockerfile.dev
      sync: 
        manual: 
          - src: 'src/**/*.js'
            dest: .
          - src: 'src/**/*.css'
            dest: .
          - src: 'src/**/*.html'
            dest: .
deploy:
  kubectl:
    manifests:
      - k8s/*